version: '3'

services:
  db:
    image: mysql:5.7
    restart: always
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: laravel
    networks:
      - app-networks
    volumes:
      - ./data/mysql:/var/lib/mysql
networks:
  app-networks:
    driver: bridge
